data_path : "/workspace/Dataset/FSI/" # Root Path for the dataset

synthetic_path : "submission/syn_submission.csv"
test_path : "test.csv" # relative path to the data_path
num_classes : 13
use_all : False

model : model_v2

model_path : "/workspace/Personal_Development/Dacon_FSI/classifier/run/train5/best_model.pt"

dataset :  CSV_Binary_dataset # CSV_Binary_dataset, CSV_Regression_dataset

blocks : 8
alpha : 30 # additional columns
dimension : 256 # for each columns
random_seed : 101

input_size : 62

batch_size : 128

threshold : 0.5

test : True
